name: "Add badge"
description: "Users can see them on the scroll canvas and mint them."
title: "[Badge]: "
labels: ["new"]
body:
  - type: input
    id: badgeContract
    attributes:
      label: Badge Contract Address
      description: Address of badge contranct deployed on Scroll, for permissionless minting, no need
      placeholder: "0xB1Dbd079c62d181926E5A54932Bb1b15F760e8A0"
    validations:
      required: true
  - type: input
    id: attesterProxy
    attributes:
      label: Attester Proxy Address
      description: Address of proxy attestation contract deployed on Scroll
      placeholder: "0xC47300428b6AD2c7D03BB76D05A176058b47E6B0"
    validations:
      required: true
  - type: input
    id: baseUrl
    attributes:
      label: BaseURL of Check/Claim API
      description: "like {{baseURL}}/check and {{baseURL}}/claim, refer to https://scrollzkp.notion.site/Badge-APIs-95890d7ca14944e2a6d34835ceb6b914"
    validations:
      required: true
  - type: input
    id: issuerName
    attributes:
      label: Issuer Name
      description: Name of badge issuer. Please try to keep it consistent with the one listed on https://scroll.io/ecosystem.
      placeholder: "Scroll"
    validations:
      required: true
  - type: input
    id: issuerURL
    attributes:
      label: Issuer URL
      description: URL of the badge promotional page, If left blank, it defaults to the issuer’s website on https://scroll.io/ecosystem.
      placeholder: "https://scroll.io"
    validations:
      required: false
